name: CI / cd . / make spell_check

on:
  push:
    branches: [master, v0.1, v0.2]
  pull_request:

permissions:
  contents: read

jobs:
  codespell:
    name: (Check for spelling errors)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install toml codespell==2.3.0 jupytext

      - name: Codespell
        uses: codespell-project/actions-codespell@v2.1
